spring:
  datasource:
    url: jdbc:h2:file:./.data/devdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
app:
  jwt:
    secret: "change-this-dev-secret-change-this-dev-secret-32-bytes"
  files:
    dir: "uploads"
springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: dev-pg
  datasource:
    url: jdbc:postgresql://localhost:5432/edutracker
    username: edutracker
    password: edutracker
